### ISSUE TITLE
Issues with Saved Settings

### ISSUE THREAD

**Issue by codemann8** [Berserker66/MultiWorld-Utilities#101]
1) Can you make it so the settings.json file doesn't get wiped away EVERY time we install a new version?

2) Can you give us the option to save somewhere else that isn't %Documents%\AlttpDoorRandomizer? I tried adding a value to the settings.json for "outputpath", which makes the correct directory open when you click the "Open Output Directory' button, but upon seed generation, it ignores that and saves to the default path anyways.

**Comment by Berserker66** [comment]
Config and Data files like settings.json is supposed to be in their own data/resources folders to allow proper bundling by python. Doors doesn't do that. We're looking into changing that upstream in aerinon's doors, as it should be done there.

As for the output, I'm looking into changing it over to a common /Output folder across all methods to generate a seed - haven't gotten to it yet, sorry.

**Comment by Berserker66** [comment]
second issue continued in https://github.com/Berserker66/MultiWorld-Utilities/issues/104
