### ISSUE TITLE
Sprite window too tall

### ISSUE THREAD

**Issue by WindFox** [Berserker66/MultiWorld-Utilities#126]
The sprite window is too tall for most screens. Maybe have the number per row be dynamic on how wide the window is? I seems that the window can be maximized, but does nothing useful if the list of sprites doesn't resize with it.

**Comment by Berserker66** [comment]
The window was recently widened, needing 1024 pixels vertical which should be available on just about any device made in the last 2 decades.
![image](https://user-images.githubusercontent.com/3189725/88747001-2b294280-d14e-11ea-9adc-8ef2c92b3b69.png)

**Comment by Berserker66** [comment]
Regardless, this should work for you:
https://github.com/Berserker66/MultiWorld-Utilities/commit/445852d3fa1a0320932718b935d42619736e73ca
You can now make it real narrow if you want:
![image](https://user-images.githubusercontent.com/3189725/88750037-e654da00-d154-11ea-884c-2aecc0d9bdb4.png)
