### ISSUE TITLE
Doors Branch Output Directory

### ISSUE THREAD

**Issue by codemann8** [Berserker66/MultiWorld-Utilities#131]
Can we please have the ROM get outputted to the directory specified in "output_path" instead of a directory that seems to change during random update versions?

**Comment by Berserker66** [comment]
That was supposed to be the case with 2.5. Based on your comment it appears we missed something. Can you please let us know where specifically we made a mistake?

**Comment by codemann8** [comment]
I'm not sure, but the seeds are now going to ./output as mentioned in #104 instead of a output_path which is a folder on a different drive with All Users access permissions.

**Comment by Berserker66** [comment]
I'm back to a computer that can debug this Sunday at the earliest, I'll look into it shortly after.

**Comment by Berserker66** [comment]
Ok, I think we had a bit of a misunderstanding; as it is on 2.5 /output was made the default output for everything and if you define something else in host.yaml that is under the "MultiMystery" section, so it only changes that.
For ~ 2.6 the intention is to absorb MultyMystery into Mystery and in that refactor that option will also be generalized for all outputs.

**Comment by Berserker66** [comment]
This should be fixed with https://github.com/Berserker66/MultiWorld-Utilities/commit/8852ec9a1896d02df2c6ae22ac3e0834ce1ad109 when it makes it's way into /doors
