### ISSUE TITLE
Error: 'int' object is not subscriptable on generation custom items

### ISSUE THREAD

**Issue by mopquill** [Berserker66/MultiWorld-Utilities#136]
Hey, I just wanna preface by thanks for forking/writing this, my friends and I have a lot of fun playing multiworld together!

Steps to reproduce bug:

1. Open BerserkerMultiCreator.exe from the 2.5.0 release.
2. Select the ROM, and check the box titled "Use custom item pool"
3. You can put in users or whatever if you want, but click "Generate Patched ROM".

You should not get the error in the title, with the following output in the console.

```
Shuffling the World about.
Generating Item Pool.
'int' object is not subscriptable
Traceback (most recent call last):
  File "gui.py", line 504, in generateRom
  File "Main.py", line 132, in main
  File "ItemList.py", line 223, in generate_itempool
  File "ItemList.py", line 612, in make_custom_item_pool
TypeError: 'int' object is not subscriptable
```

**Comment by Berserker66** [comment]
Thank you for spotting this, will be fixed with the next update.
