### ISSUE TITLE
Mystery Plando issues

### ISSUE THREAD

**Issue by KonoTyran** [Berserker66/MultiWorld-Utilities#156]
Trying to put plando items into Mode/Goal related locations causes the seed generation to fail locking that mode/goal from being possible in mystery weights.

for an example: you try to place a sword on links uncle, while having a 50/50 chance of standard/open. every attempt to make a standard seed will fail because standard places a weapon on uncle first.

solution 1: if plando item fails due to goal/mode incompatibility fail to place item and continue generating.
solution 2: allow us to specify plando items per mode/goal

**Comment by Berserker66** [comment]
solution 3: add a "force" parameter that when false will attempt to place item, but log a warning when it didn't work?

**Comment by CaitSith2** [comment]
solution 3 implemented in a6d53aafb073ceb435b24e518deefd48ad202b98

**Comment by KonoTyran** [comment]
only issue I have with logging a warning is that it could give away some of the mystery when you see that pop up in the console when generating seeds. so maybe an option for "force = silent" to allow for no warning being displayed to keep the mystery?

**Comment by KonoTyran** [comment]
I see my last concern was addressed in #55b4820 <3

**Comment by Berserker66** [comment]
This has been implemented via various `force:` settings (silent, force, ignore)
