### ISSUE TITLE
Feature request: remove screen flashing during particular scenes.

### ISSUE THREAD

**Issue by wolfman2000** [Berserker66/MultiWorld-Utilities#164]
Certain scenes can be intense for the eyes of some players and viewers of streams due to the flashing that takes place. If there is a way to make it so that these scenes can be redone without the flashing effect (and not changing the game speed at the same time), that would be great.

These scenes include the following:

* End of the intro cutscene.
* Just before Aga 1.
* I forget if the actual lightning attacks flash too.

This option would be added as a personal option that does not affect the randomization, similar to heart color.

**Comment by Berserker66** [comment]
I heard a while ago that someone was working on something like that. But I don't remember who and I have no idea what became of this, I lost track of this potential feature.

So, a good first step would be to see where that work went.

**Comment by pepperpow** [comment]
Some new experimental options are written in this branch.

https://github.com/pepperpow/MultiWorld-Utilities/tree/adjust_options

With reduceflashing enabled, it should remove all instances of aga flashes (they're both the same routine), ether flashing and lightning from rain.  untested vitreous flashing but it should have the same routine as aga's lightning...

**Comment by Berserker66** [comment]
pepper's options got added, closing this issue.
