### ISSUE TITLE
Suggestion: Ice Rod Hunt + Bee Traps

### ISSUE THREAD

**Issue by marcmagus** [Berserker66/MultiWorld-Utilities#170]
In Ice Rod Hunt games, Bee Traps would masquerade better if there were a way to special case it so they always appear to be an ice rod. This would also make Ice Rod Hunt more compelling as you'd get more moments of excitement/disappointment.

**Comment by Berserker66** [comment]
you'd actually catch on pretty quick that they're all ice rods. There's a 1 in 64 that it happens to look like an ice rod, which has gotten a few people already. This change would also run the risk that you might not notice that you just got the ice rod.

**Comment by marcmagus** [comment]
I imagined you'd know immediately they're all looking like ice rods. Every time you saw one you'd still have "maybe this one's a real ice rod?" whereas right now it's almost exclusively "whatever that is it's not an ice rod, ignore"

Elevated risk of missing win condition is real and a serious design concern.

For the specific case of Ice Rod Hunt, is being able to figure out it's a bee trap by observation more good or bad? (In the general case it's definitely good, and it might be that the special case isn't worth having a special case even if it played better)

**Comment by Berserker66** [comment]
Ah, my default assumption was multiworld, where youd still collect non ice rods for the team.

**Comment by marcmagus** [comment]
Ah, yes, I was thinking of single player ice rod hunt (which I tried yesterday) or multiworld all doing ice rod hunt. I can see that as soon as you go to mixed multiworld it's not so relevant. Probably not worth the carrying cost for the special case.

I was considering suggesting as an alternative that they just won't look like something you already have, which would make more ice rods in ice rod hunt and be interesting in all modes, but I'm not sure what that means in a multiworld context or if it's worth the effort.

**Comment by Berserker66** [comment]
The alternative suggestion would need a lot of comparing using a snes cpu, which would slow things down quite a bit when loading the sprite. Which might actually be a long enough hitch that you'd be able to tell from that alone.
