### ISSUE TITLE
This program can only be installed on versions of windows designed für x64

### ISSUE THREAD

**Issue by TheTommynator** [Berserker66/MultiWorld-Utilities#179]
I'm trying to get multiworld running on a Windows ARM version.

I need to rely on this because I use a M1 Mac which can only emulate an ARM version of windows.

But as the installer starts I'm getting the error above. Is there a version which may on ARM windows?

**Comment by Berserker66** [comment]
You can run the source directly, for which you can find instructions at https://github.com/Berserker66/MultiWorld-Utilities/wiki/Running-from-source. As I don't have a Windows ARM device I cannot compile for that platform. If you need more help with getting it to run, the faster method may be to use discord https://discord.com/invite/8Z65BR2, but you are welcome to post here too.
