### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by srrobin83** [Berserker66/MultiWorld-Utilities#180]
Hello,

I updated to the latest MultiWorld, and I cannot seem to run BerzerkerMultiMystery without running into the following error.

Berserker55's MultiMystery Launcher
Found player's file weightedSettings.yaml.
1 Players found.
BerserkerMystery.exe --multi 1 --p1 "Players\weightedSettings.yaml"  --rom "Zelda no Densetsu - Kamigami no Triforce (Japan).sfc" --enemizercli "EnemizerCLI/EnemizerCLI.Core.exe" --outputpath "output" --teams 1 --plando "bosses" --create_spoiler --create_diff --glitch_triforce
Traceback (most recent call last):
  File "__startup__.py", line 74, in run
  File "Console.py", line 36, in run
  File "Mystery.py", line 809, in <module>
  File "Mystery.py", line 221, in main
  File "Mystery.py", line 299, in handle_name
  File "string.py", line 167, in vformat
  File "string.py", line 207, in _vformat
  File "string.py", line 272, in get_field
  File "string.py", line 227, in get_value
IndexError: tuple index out of range
Traceback (most recent call last):
  File "MultiMystery.py", line 133, in <module>
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command 'BerserkerMystery.exe --multi 1 --p1 "Players\weightedSettings.yaml"  --rom "Zelda no Densetsu - Kamigami no Triforce (Japan).sfc" --enemizercli "EnemizerCLI/EnemizerCLI.Core.exe" --outputpath "output" --teams 1 --plando "bosses" --create_spoiler --create_diff --glitch_triforce' returned non-zero exit status 1.

I tried using my previous player files, but that didn't work, so I tried the default one. I left the template name as is, and changed the player name to "Test{1}". I also tried doing a complete uninstall and reinstall of Berzerker MultiWorld as a whole, with no change to the error.

Thank you for your time, and any assistance you might be able to offer.

**Comment by Berserker66** [comment]
If you want to use { and } you would have to escape them, as it stands you're instructing the generator to pull the second item of a list into the name, a list of 0 positional members. "Test{{1}}" should therefore work.

**Comment by srrobin83** [comment]
Awesome! Thank you for the prompt reply. That seems to have worked. The default player file seems a bit misleading as it lists "YourName{number}" by default.

This is also a part of the new player file I don't quite understand as well. What is a slot number? Is this for if you are trying to run teams or does it serve some other function?

Thank you again for your time and prompt assistance.

**Comment by Berserker66** [comment]
slot number is just a player ID, it starts at 1 and increments for each player. anything in {} is a variable that gets filled in and names have to be unique. So by using the ID as a variable in a name you can have the default file multiple times and the players will have unique names, in this case "YourName1" and "YourName2"
