### ISSUE TITLE
Binary patches not created

### ISSUE THREAD

**Issue by CaitSith2** [Berserker66/MultiWorld-Utilities#44]
I found a bug where if you specify to Not zip the roms, but only zip the binary patches, the binary patches are NOT even created at all.

**Comment by CaitSith2** [comment]
https://github.com/Berserker66/MultiWorld-Utilities/blob/master/MultiMystery.py#L123 - I noticed just now a lack of zip_diffs in that line, which 100% explains why no diffs are created.

**Comment by Berserker66** [comment]
Thank you
