### ISSUE TITLE
Utilities 1.9 Doors Module error

### ISSUE THREAD

**Issue by draguscloud** [Berserker66/MultiWorld-Utilities#63]
The Doors version of the release is failing to generate seeds and reporting: 
ModuleNotFoundError: No module named 'pkg_resources.py2_warn

**Comment by Berserker66** [comment]
Yep in the doors update that was merged in I found this beautiful line:
`installed_packages = [str(d) for d in pkg_resources.working_set]   #this doesn't work from the .exe either, but it doesn't crash the program`

Yeah, about that. It does crash the program. I've now tucked away the offending code in such a way that in most cases it won't trigger and the exe should work, unless you try to run diagnostics which will fail.

Anyway, I've reuploaded Doors with a hotfix. Please try it and let me know if it is fixed for you.

**Comment by Berserker66** [comment]
No reply and appears to be fixed, so closed.
