### ISSUE TITLE
Separate Auto forfeit and manual forfeit mode

### ISSUE THREAD

**Issue by trippsc2** [Berserker66/MultiWorld-Utilities#86]
Hey.  Would it be much trouble to separate out the manual forfeit mode setting and the auto forfeit on goal completion?  My friend group plays pretty casually and would like to be able to drop out manually, but the auto forfeit is also convenient for us.

**Comment by Berserker66** [comment]
You can open host.yaml and set forfeit to always on, always off, allowed after goal and automatic after goal. You can also change the setting and restart the server and it will continue on with the new setting from that point.

Sounds like you're looking to set it to enabled? Or are you specifically looking for enabled plus automatic?

**Comment by trippsc2** [comment]
Yeah, I'm looking for enabled plus auto.  Is it feasible to de-couple those options, since one is about putting in the command and the other is the auto forfeit for beating the world?
